language: java
before_install:
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar -zxf android-sdk_r21.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android list sdk
  - android update sdk --filter 1,14 --no-ui --force
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.net#miu-dev" 
    use_notice: true
    skip_join: true
